server:
  port: 8848
spring:
  application:
    name: springbootinit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/my_init
    username: root
    password: 123456
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
mybatis-plus:
  type-aliases-package: com.zkflzl.myinit.entity # 别名扫描包
  configuration:
    map-underscore-to-camel-case: false #取消驼峰转下划线
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句
logging:
  level:
    com.zkflzl: debug
  pattern:
    dateformat: mm:ss.SSS
